### ISSUE TITLE
Wrong examples in headless documentation

### ISSUE THREAD

**Issue by uf0** [kirby-tools/kirby.tools#13]
### Environment

Kirby Tools documentation

### Describe the bug

https://github.com/kirby-tools/kirby.tools/blob/8eaf67b36d1fdf7dcd0745e9edae609bd5a30f7c/content/1.docs/3.headless/2.usage.md?plain=1#L79

it should be `Authorization` and not `Authentication`

same here:
https://github.com/kirby-tools/kirby.tools/blob/8eaf67b36d1fdf7dcd0745e9edae609bd5a30f7c/content/1.docs/3.headless/2.usage.md?plain=1#L185

**Comment by johannschopplich** [comment]
Good catch, thanks! 😊
